### PR TITLE
fix: add `baseUrl` to `tsconfig.json`

### LINKED ISSUE #68: `vite build` warning
I'm getting the following warning when building for production:

```
❯ yarn build
yarn run v1.22.10
$ vite build
 > tsconfig.json:9:16: warning: Non-relative path "resources/*" is not allowed when "baseUrl" is not set (did you forget a leading "./"?)
    9 │                 "resources/*"
      ╵                 ~~~~~~~~~~~~~

vite v2.1.5 building for production...
```

When changing it to `./resources/*` in `vite.config.ts`, the warning disappears, but laravel-vite seems to reset it to its original value again.

### PR DESCRIPTION
**Pull request by kabouzeid**
`baseUrl` must always be set when `paths` is set (https://www.typescriptlang.org/tsconfig#paths).

### CODE REVIEW

File: src/Commands/GenerateAliasesCommand.php [hunk 1]
```diff
@@ -47,6 +46,7 @@ protected function createTsConfig(): void
     protected function writeAliases(): void
     {
         $tsconfig = json_decode(File::get($this->getTsConfigPath()), true);
+        $tsconfig['compilerOptions']['baseUrl'] = '.';
         $tsconfig['compilerOptions']['paths'] = collect(\config('vite.aliases'))
```
Comment (kabouzeid) [inline src/Commands/GenerateAliasesCommand.php:50]: In future, we should first check whether `baseUrl` is `null` or `'.'` before proceeding.
Also `paths` should be merged with existing paths.

Something like the following pseudo code:
```
if (baseUrl == null || baseUrl == '.' || baseUrl == './') {
    baseUrl = '.'
    paths = merge(paths, newPaths)
} else {
    print("Error: Can't automatically set paths when custom baseUrl is set.")
}
```

Comment (innocenzi) [reply src/Commands/GenerateAliasesCommand.php:50]: > In future, we should first check whether baseUrl is null or '.' before proceeding.

What's the reason for this?

> Also paths should be merged with existing paths.

Good call. Thanks!

Comment (kabouzeid) [reply src/Commands/GenerateAliasesCommand.php:50]: When `baseUrl` is not `null`, `.` or `./`, then we can't assume that eg `{baseUrl}/resources` points to the location we intended. More likely in this case the user knows what they are doing.
